### PR TITLE
New pathway file for RHEL8 Workshop

### PR DESCRIPTION
**Pull request by gsoria**
This pathway file will be used for George P. Johnson (India partner)'s RHEL8 workshop

Signed-off-by: Gabriela S. Soria <soria.gaby@gmail.com>

### CODE REVIEW

**Review by danarbaugh — APPROVED** [review]

**Review by rfallin — APPROVED** [review]

**Comment by RoshiniRaheja** [comment]
Hi,

**Comment by RoshiniRaheja** [comment]
Please share the pathway link for approval

**Comment by gsoria** [comment]
Hi @RoshiniRaheja the pathway is included in this PR, you can see it in the tab `Files changed`

**Review by RoshiniRaheja — APPROVED** [review]
Hi, 

Looks fine to me, as per the content available @rhel-labs.com

Request you to check once.

**Review by RoshiniRaheja — APPROVED** [review]

**Comment by RoshiniRaheja** [comment]
[image: image.png]


Regards,



Roshini Raheja

Account Manager, Audience Marketing




We Power Brand Experiences.



A Project Worldwide Agency

www.gpjindia.com
<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gpjindia.com%2F&data=02%7C01%7CRoshini.Raheja%40gpj.com%7C219aa2ea5d264c2e989408d6e338b026%7C8eaa3b9eddf5409e87bfdf1edbbeaf70%7C0%7C0%7C636946229950179772&sdata=dxhp3AoKrcLlHY2RFFVyGI5iT8xowwfv5%2BaIPhH2nTI%3D&reserved=0>
| George P. Johnson is the world¹s leading experiential marketing agency.
We unleash the power of creativity to deliver experiences that elevate
brands and drive tangible results. We¹re part of Project, an independent
network in service of creativity. Project’s agencies include George P.
Johnson, Wondersauce, Dark Horse, Praytell, Partners + Napier, ARGONAUT,
Motive, Spinifex Group, G7 Entertainment Marketing, School, Raumtechnik,
Shoptology, and Pitch.



This e-mail may contain confidential or privileged information. If you are
not the intended recipient, please delete it and notify the sender of the
error.



*Bangalore:*

401, 3rd Floor | Prestige Tudor Court | 40, Lavelle Road | Bangalore 560 001

Mobile : +91: 7760226467 | Board : +918022113684

Email: roshini.raheja@gpj.com



*Mumbai:*

Level 5, Spectrum Towers, Chincholi Bunder Road, Mindspace, Malad West,
Mumbai -400064 , Maharashtra



*Delhi:*

No 410 | Bestech Chambers | Sushantlok 1 | Gurgaon - 122002

**Comment by RoshiniRaheja** [comment]
Hi Team, 

The lab environment created for us has 13 modules, whereas we require only 7. Could you please look into it.

**Comment by RoshiniRaheja** [comment]
Hi Rob,

We see there are #13 modules available for the lab environment created for
our workshop.

Is it possible to have only 7 modules that are required; Because
participants might get confused.

Module # Module Title
Module 1 Managing System Updates Using the Web Console
Module 2 Creating Images with Container Tools (buildah)
Module 3 Deploying Containers Using Container Tools (podman)
Module 4 Managing Software From an Application Stream
Module 5 Using Web Console to build virtual machine images (Image Builder)
Module 6 Configuring System-wide Crypto Policy
Module 7 Using Red Hat Insights


Regards,



Roshini Raheja

Account Manager, Audience Marketing




We Power Brand Experiences.



A Project Worldwide Agency

www.gpjindia.com
<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gpjindia.com%2F&data=02%7C01%7CRoshini.Raheja%40gpj.com%7C219aa2ea5d264c2e989408d6e338b026%7C8eaa3b9eddf5409e87bfdf1edbbeaf70%7C0%7C0%7C636946229950179772&sdata=dxhp3AoKrcLlHY2RFFVyGI5iT8xowwfv5%2BaIPhH2nTI%3D&reserved=0>
| George P. Johnson is the world¹s leading experiential marketing agency.
We unleash the power of creativity to deliver experiences that elevate
brands and drive tangible results. We¹re part of Project, an independent
network in service of creativity. Project’s agencies include George P.
Johnson, Wondersauce, Dark Horse, Praytell, Partners + Napier, ARGONAUT,
Motive, Spinifex Group, G7 Entertainment Marketing, School, Raumtechnik,
Shoptology, and Pitch.



This e-mail may contain confidential or privileged information. If you are
not the intended recipient, please delete it and notify the sender of the
error.



*Bangalore:*

401, 3rd Floor | Prestige Tudor Court | 40, Lavelle Road | Bangalore 560 001

Mobile : +91: 7760226467 | Board : +918022113684

Email: roshini.raheja@gpj.com



*Mumbai:*

Level 5, Spectrum Towers, Chincholi Bunder Road, Mindspace, Malad West,
Mumbai -400064 , Maharashtra



*Delhi:*

No 410 | Bestech Chambers | Sushantlok 1 | Gurgaon - 122002

**Comment by RoshiniRaheja** [comment]
Hi Rob,

The URL shows below error for the module "Using Web Console to Build
Virtual Machine Images" (Image Builder)

Please check.

[image: image.png]



Regards,



Roshini Raheja

Account Manager, Audience Marketing




We Power Brand Experiences.



A Project Worldwide Agency

www.gpjindia.com
<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gpjindia.com%2F&data=02%7C01%7CRoshini.Raheja%40gpj.com%7C219aa2ea5d264c2e989408d6e338b026%7C8eaa3b9eddf5409e87bfdf1edbbeaf70%7C0%7C0%7C636946229950179772&sdata=dxhp3AoKrcLlHY2RFFVyGI5iT8xowwfv5%2BaIPhH2nTI%3D&reserved=0>
| George P. Johnson is the world¹s leading experiential marketing agency.
We unleash the power of creativity to deliver experiences that elevate
brands and drive tangible results. We¹re part of Project, an independent
network in service of creativity. Project’s agencies include George P.
Johnson, Wondersauce, Dark Horse, Praytell, Partners + Napier, ARGONAUT,
Motive, Spinifex Group, G7 Entertainment Marketing, School, Raumtechnik,
Shoptology, and Pitch.



This e-mail may contain confidential or privileged information. If you are
not the intended recipient, please delete it and notify the sender of the
error.



*Bangalore:*

401, 3rd Floor | Prestige Tudor Court | 40, Lavelle Road | Bangalore 560 001

Mobile : +91: 7760226467 | Board : +918022113684

Email: roshini.raheja@gpj.com



*Mumbai:*

Level 5, Spectrum Towers, Chincholi Bunder Road, Mindspace, Malad West,
Mumbai -400064 , Maharashtra



*Delhi:*

No 410 | Bestech Chambers | Sushantlok 1 | Gurgaon - 122002

**Comment by RoshiniRaheja** [comment]
Below 2 learning scenario had following error:-

1) "Using Web Console to Build Virtual Machine Images" (Image Builder)
[image: image.png]

2) Using Red Hat Insights

[image: IMG-20201124-WA0017.jpg]
[image: IMG-20201124-WA0016.jpg]




Regards,



Roshini Raheja

Account Manager, Audience Marketing




We Power Brand Experiences.



A Project Worldwide Agency

www.gpjindia.com
<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gpjindia.com%2F&data=02%7C01%7CRoshini.Raheja%40gpj.com%7C219aa2ea5d264c2e989408d6e338b026%7C8eaa3b9eddf5409e87bfdf1edbbeaf70%7C0%7C0%7C636946229950179772&sdata=dxhp3AoKrcLlHY2RFFVyGI5iT8xowwfv5%2BaIPhH2nTI%3D&reserved=0>
| George P. Johnson is the world¹s leading experiential marketing agency.
We unleash the power of creativity to deliver experiences that elevate
brands and drive tangible results. We¹re part of Project, an independent
network in service of creativity. Project’s agencies include George P.
Johnson, Wondersauce, Dark Horse, Praytell, Partners + Napier, ARGONAUT,
Motive, Spinifex Group, G7 Entertainment Marketing, School, Raumtechnik,
Shoptology, and Pitch.



This e-mail may contain confidential or privileged information. If you are
not the intended recipient, please delete it and notify the sender of the
error.



*Bangalore:*

401, 3rd Floor | Prestige Tudor Court | 40, Lavelle Road | Bangalore 560 001

Mobile : +91: 7760226467 | Board : +918022113684

Email: roshini.raheja@gpj.com



*Mumbai:*

Level 5, Spectrum Towers, Chincholi Bunder Road, Mindspace, Malad West,
Mumbai -400064 , Maharashtra



*Delhi:*

No 410 | Bestech Chambers | Sushantlok 1 | Gurgaon - 122002

**Comment by RoshiniRaheja** [comment]
Request your quick intervention and action. We cannot afford to have the
same issue persisting the next couple of days too..

Thanks in advance.


*STAY SAFE **Best Regards, *

*Krishna Kumar Puravoor (KK)*
Marketing, Red Hat India Pvt. Limited
# +91- 9972844556


TRIED. TESTED. TRUSTED. <https://redhat.com/trusted>

**Comment by RoshiniRaheja** [comment]
Hi, 

Can you please guide me on how to merge the open PR for the workshop pathway.

**Comment by RoshiniRaheja** [comment]
Hi, 

Look's like, I don't have 'write access' to this repository to merge pull requests.  Can you please do the modifications at your end and get them merged. 

We require lab setup for only 7 modules. 

Thanks for your help!

**Comment by RoshiniRaheja** [comment]
Hi,

Greetings!

Sorry for too many email requests.

Can you please do one round of testing for tomorrow's workshop?
https://www.katacoda.com/rhel-labs/training/rhel8-workshop-26

Like for the 25th Nov workshop, Request you to check the learning
instructions are working fine.

Today the lab environment was working fine. Only 1-2 delegates had
authentication issues and images were not there for the "Deploying
Containers Using Container Tools (podman)" module. Even after, the lab
instructor had asked to close the lab and start a new one. Still the error
occurred.
(This error occurred for 2 delegates)

Rest, everything was fine.

Thank you for helping us out; I really appreciate your support.



Regards,



Roshini Raheja

Account Manager, Audience Marketing




We Power Brand Experiences.



A Project Worldwide Agency

www.gpjindia.com
<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gpjindia.com%2F&data=02%7C01%7CRoshini.Raheja%40gpj.com%7C219aa2ea5d264c2e989408d6e338b026%7C8eaa3b9eddf5409e87bfdf1edbbeaf70%7C0%7C0%7C636946229950179772&sdata=dxhp3AoKrcLlHY2RFFVyGI5iT8xowwfv5%2BaIPhH2nTI%3D&reserved=0>
| George P. Johnson is the world¹s leading experiential marketing agency.
We unleash the power of creativity to deliver experiences that elevate
brands and drive tangible results. We¹re part of Project, an independent
network in service of creativity. Project’s agencies include George P.
Johnson, Wondersauce, Dark Horse, Praytell, Partners + Napier, ARGONAUT,
Motive, Spinifex Group, G7 Entertainment Marketing, School, Raumtechnik,
Shoptology, and Pitch.



This e-mail may contain confidential or privileged information. If you are
not the intended recipient, please delete it and notify the sender of the
error.



*Bangalore:*

401, 3rd Floor | Prestige Tudor Court | 40, Lavelle Road | Bangalore 560 001

Mobile : +91: 7760226467 | Board : +918022113684

Email: roshini.raheja@gpj.com



*Mumbai:*

Level 5, Spectrum Towers, Chincholi Bunder Road, Mindspace, Malad West,
Mumbai -400064 , Maharashtra



*Delhi:*

No 410 | Bestech Chambers | Sushantlok 1 | Gurgaon - 122002

**Comment by RoshiniRaheja** [comment]
Hi,

Below is the error instance that occurred for one of the learning
scenarios, during today's workshop.

"Deploying Containers with Containers tools". Step 1: Images are not
available.

[image: IMG-20201126-WA0001.jpg]



Sent on November 25, 2020 5:11:16 PM PST
>

**Comment by smcbrien** [comment]
Please send this to katacodasupport@oreilly.com

**Pull request closed without merging**
